### ISSUE TITLE
About correction

### ISSUE THREAD

**Issue by laxmangeo** [esrivas17/gacos_correction_for_GMTSAR#14]
Dear Author,
I apply Gacos_correction  to unwrapped phase, output files are phasefilt_GACOS_corrected.grd, phasefilt_GACOS_corrected_detrended.grd. Again should i unwrap one of this file(phasefilt_GACOS_corrected.grd or phasefilt_GACOS_corrected_detrended.grd) for SBAS? or phasefilt_GACOS_corrected.grd use for SBAS?

**Comment by erik-17** [comment]
Hi, you should apply the correction to unwrapped interferograms. then those corrected gris should be use in SBAS. However, which one you apply depends on the type of deformation you are analyzing, if you are interested in long wavelength signals it is recommended to not use the detrended grids. Conversely, if you are interested in short wavelength signals (subsidence for instance) then I think it's better to use the detrended grids

**Comment by laxmangeo** [comment]
Thank you sir, i will do

**Comment by laxmangeo** [comment]
Thank you sir, you mean  phasefilt_GACOS_corrected.grd or phasefilt_GACOS_corrected_detrended.grd used for SBAS right.

**Comment by erik-17** [comment]
> Thank you sir, you mean phasefilt_GACOS_corrected.grd or phasefilt_GACOS_corrected_detrended.grd used for SBAS right.

yes that's correct

**Comment by laxmangeo** [comment]
Thank you sir, I will do
