### ISSUE TITLE
How do I use GACOS_correction.csh in sbas processing?

### ISSUE THREAD

**Issue by MinervaLee0429** [esrivas17/gacos_correction_for_GMTSAR#15]
Dear professor, I have a question to ask, because I am doing SBAS-INSAR processing, I want to use the script GACOS_correction.csh for correction, but because I am doing it under the processing flow of sbas, and I also see some opinions in the forum that this script can only be used after unwrap. At the same time, SBAS is unwrapped after merging multiple subwaths. I would like to know whether GACOS_correction.csh can correct the interference pattern in the merge folder after merging and unwrapping. If yes, do I need to change the merge folder? What changes, if any, should be made? I would really appreciate it if you could answer me.

**Comment by esrivas17** [comment]
Hi, yes you must apply the correction to unwrapped interferograms. if you have merged multiple subswaths, you should point to the folder where your unwrap.grd files are. I think that originally the code was not meant to be applied to merged subswaths (I cant remember what was the problem) but I think it should work.

**Comment by MinervaLee0429** [comment]
Thank you very much for your reply. I will try it.

**Comment by MinervaLee0429** [comment]
Dear Professor, I tried to run the GACOS_correction.csh script in the merge folder but the following error occurred. 
![截图 2023-11-24 18-01-28](https://github.com/esrivas17/gacos_correction_for_GMTSAR/assets/147982617/0721bceb-5f97-4562-9078-503f3766e441)
this is my merge folder and one of the merged interferogram folders.
![截图 2023-11-24 18-21-00](https://github.com/esrivas17/gacos_correction_for_GMTSAR/assets/147982617/e5911fbb-d15a-4bca-817c-af6e52988098)
![截图 2023-11-24 18-40-57](https://github.com/esrivas17/gacos_correction_for_GMTSAR/assets/147982617/9195626c-3484-4856-9a3a-003adb394e75)
 There are also the topo folders created by following the instructions, 
![截图 2023-11-24 18-29-33](https://github.com/esrivas17/gacos_correction_for_GMTSAR/assets/147982617/8d811a70-5544-4ba9-baec-b78743e3ed12)
and the folders where the GACOS data resides.
![截图 2023-11-24 18-26-05](https://github.com/esrivas17/gacos_correction_for_GMTSAR/assets/147982617/2931fd8f-c9af-43f4-880c-0d37bc16b0d4)
Please guide me on how to solve this error. I have not been able to find the example of applying GACOS_correction.csh script in sbas processing, so please help me solve this problem and make the script work.

**Comment by MinervaLee0429** [comment]
Dear Professor, I tried to run the GACOS_correction.csh script in the merge folder but the following error occurred.
![截图 2023-11-24 18-01-28](https://github.com/esrivas17/gacos_correction_for_GMTSAR/assets/147982617/013d881c-e473-4ff1-b3df-7c7549c8ac1f)

 this is my merge folder and one of the merged interferogram folders.
![截图 2023-11-24 18-21-00](https://github.com/esrivas17/gacos_correction_for_GMTSAR/assets/147982617/747db85c-d66f-4bab-9b16-2ea14c8534cd)
![截图 2023-11-24 18-40-57](https://github.com/esrivas17/gacos_correction_for_GMTSAR/assets/147982617/1a3977fd-1774-4bb1-94d5-7702fa4bfa9a)

 There are also the topo folders created by following the instructions, 
![截图 2023-11-24 18-40-57](https://github.com/esrivas17/gacos_correction_for_GMTSAR/assets/147982617/359851da-5246-405c-9320-5b958e5a46ba)

and the folders where the GACOS data resides.
![截图 2023-11-24 18-26-05](https://github.com/esrivas17/gacos_correction_for_GMTSAR/assets/147982617/6704fd75-239e-44d5-98bf-e1f7c316c628)
Please guide me on how to solve this error. I have not been able to find the example of applying GACOS_correction.csh script in sbas processing, so please help me solve this problem and make the script work.

**Comment by esrivas17** [comment]
Hi, could you show the content of your intflist file?

**Comment by esrivas17** [comment]
ALso, you are pointing wrongly to the GACOS directory

**Comment by MinervaLee0429** [comment]
@esrivas17 Hello professor, thank you for your reply, this is the content of my intflist, 
![截图 2023-11-24 21-19-39](https://github.com/esrivas17/gacos_correction_for_GMTSAR/assets/147982617/f26a1e0e-61a5-48a7-9a12-f66a3c50b077)
the path of GACOS is changed after I failed to run the script, the path is actually no problem when the screenshot. Therefore, I really do not know where the problem is, and I would like to ask you to answer this question for me.
![截图 2023-11-24 21-22-42](https://github.com/esrivas17/gacos_correction_for_GMTSAR/assets/147982617/277c8eee-4f38-4191-b851-d3221fce1b16)

**Comment by esrivas17** [comment]
Hi, checking your log files seems like you need to add some files to your "topo" directory... make sure that the file master.PRM is there. if not, try to get it from your non-merged directory. Also, copy the "date.SLC" files from your original directory to your merge directory. These files are used to get the dates of each SLC

**Comment by MinervaLee0429** [comment]
@esrivas17 Thank you for your reply, Professor. Regarding the topo folder, I saw the script prompt that requires the master.PRM file and the corresponding. LED file and dem.grd file, I merge the supermaster.PRM generated during the process as master.PRM, and find the corresponding. LED file, placed in the topo folder.

 In addition, you said "opy the "date.SLC" files from your original directory to your merge directory" is the corresponding date in each subtape. Are SLCS copied to the corresponding date interferogram folder in the merge directory? SLC, S1_20180110_100451_F1.SLC, S1_20180110_100451_F2.SLC, S1_20180110_100451_F3.SLC, S1_20180215_100450_F1.SLC, S1_20180215_1 Are 00450_F2.SLC and S1_20180215_100450_F3.SLC moved to 2018009_2018045 in the merge directory?

**Comment by MinervaLee0429** [comment]
Professor, this is my topo folder.
![截图 2023-11-24 21-51-29](https://github.com/esrivas17/gacos_correction_for_GMTSAR/assets/147982617/43b810c3-e418-4f9c-82ef-a55ecf650125)

**Comment by esrivas17** [comment]
yes, please rename your supermaster.PRM to master.PRM or you could edit the code to call the same file.
And yes, but please you would need to paste the SLC files in its corresponding directory in the merge folder

**Comment by MinervaLee0429** [comment]
@esrivas17 Hello Professor, thank you for your tireless guidance, I followed your guidance, the script did start to run, but did not produce the final result. At runtime I get this error,
![截图 2023-11-25 00-11-07](https://github.com/esrivas17/gacos_correction_for_GMTSAR/assets/147982617/5635cd02-7bed-4efc-af21-0c6edad6d38b)
![截图 2023-11-25 00-30-32](https://github.com/esrivas17/gacos_correction_for_GMTSAR/assets/147982617/33a8b395-bbc5-45cb-8dec-85af841257f1)
 I get this result in one of my folders,
![截图 2023-11-25 00-32-11](https://github.com/esrivas17/gacos_correction_for_GMTSAR/assets/147982617/f50ee64e-0820-4ae9-a7f8-bafc6c6a014a)
This is my log file,
[GACOSlog.txt](https://github.com/esrivas17/gacos_correction_for_GMTSAR/files/13461162/GACOSlog.txt)
Then I tried to use only one subband. the SLC file, while resolving “the number of SLC files is inconsistent ”at the beginning, 
![截图 2023-11-25 00-43-11](https://github.com/esrivas17/gacos_correction_for_GMTSAR/assets/147982617/3e54818e-f12d-4d0d-97a5-09f45f2d4e90)
![截图 2023-11-25 00-43-27](https://github.com/esrivas17/gacos_correction_for_GMTSAR/assets/147982617/00998859-ec42-45c3-9011-66508faffaa3)
but can not produce the final result. This is my second log file
[GACOSlog2.txt](https://github.com/esrivas17/gacos_correction_for_GMTSAR/files/13461186/GACOSlog2.txt)

**Comment by MinervaLee0429** [comment]
@esrivas17 Hello Professor, you are experiencing a situation where phasefilt_gacOS_Correct.grd and phasefilt_GACOS_corrected_detrended.grd cannot be generated
These two results have problems after the generation of szpddm_phase.grd and szpddm_phase_LOS.grd. I don't know how to solve them. Please kindly give me your guidance.

**Comment by esrivas17** [comment]
Looking at the folder you shared. You have 6 .SLC files. The scripts are designed to work with one subswath therefore it's expecting only two of these files. (1 per date). That's why you are getting the message that the SLC files are not consistent. I should work on including the option to process more than one subswath but for the moment you could leave only two SLC files (either F1, F2 or F3) and see if you can get the final grids. Also make sure your dem is larger than the coverage of GACOS.
Maybe you can comment out in operacion.csh lines 121 to 125, run the whole script again and send an image of the one of the folders to see what files are generated

**Comment by MinervaLee0429** [comment]
@esrivas17 Thank you for your response, Professor. I'll try to deal with it and see what happens.
