### ISSUE TITLE
About correction 

### ISSUE THREAD

**Issue by lamesgeo** [esrivas17/gacos_correction_for_GMTSAR#16]
Respected sir,
               I have a little query regarding correction, The correct sequence would be:
 Interferogram - Unwrapping - GACOS - SBAS
Or
Interferogram-GACOS-unwrapping-SBAS
Or 
Interferogram-Unwrapping-GACOS-Unwrapping-SBAS.

**Comment by esrivas17** [comment]
Hii.
The first one is correct. Interferograms, unwrapping, Gacos corrections then SBAS

**Comment by lamesgeo** [comment]
ok, sir, I applied GACOS to the unwrapped phase, resulting in  phasefilt_Gacos.grd and phasefilt_GACOS_Detrend.grd.
To obtain the local subsidence time series,  I selected phasefile_GACOS_Detrend.grd for SBAS. Subsequently, renamed it from  phasefilt_GACOS_Detrend to unwrap.grd (name changed old unwrap.grd) for SBAS.
Is this the correct process sir? If not, guide me.

**Comment by esrivas17** [comment]
Hi. I think you are right to keep the name "unwrap.grd" for SBAS, since those are the files that the script looks for. However, I would recommend to keep the "original" unwrap.grd in case you need to reprocess it again

**Comment by lamesgeo** [comment]
yes, sir, I keep the original unwrap.grd as a different name.
