### ISSUE TITLE
some questions about processing  the script

### ISSUE THREAD

**Issue by Luvina0503** [esrivas17/gacos_correction_for_GMTSAR#2]
Dear author,
As a beginner, I encountered difficulties in the step of GACOS calibration. I would like to ask you about GACOS_ Problems with correction.csh and operation.csh.
Sentinel data time: 2021.7.17/2021.8.10/2021.8.22/2021.9.3/2021.9.27
supermaster: 2021.9.3
Picture 1 is the file after merging and unwrapping, and Picture 2 is the content of each sub file.
Question:
1. Based on the above data, I do not understand what time should I download the GACOS data?
2. GACOS datas have only * ztd and *.ztd_ preview, no *. ztd.rsc.(Figure 3) Why is this?
3、GACOS. csh list_ interferograms full_ path_ to_ GACOS_ data full_ path_ topo reference_ point incidence_ angle
 list_ Interferograms refers to intflist (Figure 4)? In which file can they find reference_ point incidence_ angle?
4、gacos_ operation. csh master_ ztd master_ ztd. rsc slave_ ztd slave_ ztd. rsc reference_ point incidence_ angle
what date does slave_ ztd refer to?
Figure 1:
![image](https://user-images.githubusercontent.com/114629377/193720742-aa1c3df4-5e4f-4b7f-9fe7-98d3cdf9915b.png)
Figure 2:
![image](https://user-images.githubusercontent.com/114629377/193720786-b80416f3-641d-4072-b233-162f61cb6aaf.png)
Figure 3:
![image](https://user-images.githubusercontent.com/114629377/193720824-23e831b5-2d0b-45b7-94c5-3e4d358844ad.png)
Figure 4:
![image](https://user-images.githubusercontent.com/114629377/193720894-0adab727-ff6e-4fc5-bdeb-fe922de30125.png)

Thank you!

**Comment by esrivas17** [comment]
Hi, Sorry for the late response.
I don't check my Github very often, but I should.
1.- I would say you should download GACOS data around the same time of the acquisition time. This is stated in the zip file name for every S-1 data.
2.- Probably you downloaded Geotiff format. i suggest you get the binary form, the .ztd.rsc is the header files and is needed to resample and convert the data.
3.- Yes, list of interferograms refers to inftlist. Just make sure it is in the same directory you run the commands.
4.- GACOS corrections are based on atmospheric measurements that are converted to phase or meters and then applied to your interferogram. Therefore, you need GACOS from your master date and slave date, get the correction and apply it to your interferogram.

**Comment by Luvina0503** [comment]
@esrivas17 
Thank you for your answer. The problem has been solved
